const fs = require('fs-extra');
const path = require('path');
const logger = require('../utils/logger');
const { getServerConfigPath, getWorldsDir } = require('../utils/paths');

// 配置字段白名单 Schema
const CONFIG_SCHEMA = {
  world:        { type: 'path',     required: false, maxLength: 256, restartRequired: true  },
  worldname:    { type: 'string',   required: false, maxLength: 64,  restartRequired: true  },
  autocreate:   { type: 'enum',     values: ['1', '2', '3'],         restartRequired: true  },
  difficulty:   { type: 'enum',     values: ['0', '1', '2', '3'],   restartRequired: true  },
  maxplayers:   { type: 'number',   min: 1, max: 255,                restartRequired: true  },
  port:         { type: 'number',   min: 1024, max: 65535,           restartRequired: true  },
  password:     { type: 'string',   required: false, maxLength: 64,  restartRequired: true  },
  motd:         { type: 'string',   required: false, maxLength: 200, restartRequired: false },
  secure:       { type: 'enum',     values: ['0', '1'],              restartRequired: true  },
  language:     { type: 'string',   required: false, maxLength: 16,  restartRequired: true  },
  upnp:         { type: 'enum',     values: ['0', '1'],              restartRequired: true  },
  npcstream:    { type: 'number',   min: 0, max: 500,                restartRequired: true  },
  priority:     { type: 'number',   min: 0, max: 5,                  restartRequired: false },
};

const DEFAULT_CONFIGS = {
  vanilla: `# Terraria Server Configuration
port=7777
autocreate=3
difficulty=1
secure=1
language=zh-Hans
npcstream=60
`,
  tmodloader: `# tModLoader Server Configuration
port=7777
autocreate=3
difficulty=1
secure=1
language=zh-Hans
npcstream=60
`,
};

class ConfigService {
  constructor(stateService) {
    this.stateService = stateService;
  }

  /**
   * 读取当前模式的 serverconfig.txt
   * 返回 parsed（表单结构）和 raw（原始文本）
   */
  async getConfig(mode) {
    const configPath = getServerConfigPath(mode);
    try {
      if (await fs.pathExists(configPath)) {
        const content = await fs.readFile(configPath, 'utf8');
        return { raw: content, parsed: this._parse(content), path: configPath, mode };
      }
      const defaultContent = DEFAULT_CONFIGS[mode] || DEFAULT_CONFIGS.vanilla;
      return { raw: defaultContent, parsed: this._parse(defaultContent), path: configPath, mode };
    } catch (e) {
      logger.error('ConfigService', `Failed to read config for ${mode}`, e.message);
      throw e;
    }
  }

  /**
   * 保存配置（支持表单对象和原始文本两种方式）
   * 返回 { success, restartRequired, changedFields, backupId }
   */
  async saveConfig(mode, content, formFields) {
    const configPath = getServerConfigPath(mode);

    // 如果是表单保存（formFields 非空），通过 schema 生成配置内容
    let finalContent = content;
    if (formFields && typeof formFields === 'object') {
      finalContent = this._generateFromForm(mode, formFields);
    }

    // 读取旧配置以对比变更
    let oldParsed = {};
    try {
      const oldConfig = await this.getConfig(mode);
      oldParsed = oldConfig.parsed || {};
    } catch (e) { /* ignore */ }

    // 校验并修正配置
    const validation = this._validate(finalContent, mode);
    if (!validation.valid) {
      throw new Error(validation.errors.join('; '));
    }
    finalContent = validation.corrected || finalContent;

    // 解析新配置字段，判断哪些变了
    const newParsed = this._parse(finalContent);
    const changedFields = Object.keys(newParsed).filter(k =>
      oldParsed[k] !== newParsed[k]
    );

    // 判断是否需要重启
    const restartRequired = changedFields.some(field => {
      const schema = CONFIG_SCHEMA[field];
      return schema && schema.restartRequired;
    });

    try {
      // 1. 备份旧配置
      let backupId = null;
      if (await fs.pathExists(configPath)) {
        const bakPath = configPath + '.bak';
        await fs.copy(configPath, bakPath);
        backupId = `config_backup_${new Date().toISOString().replace(/[:.]/g, '')}`;
      }

      // 2. 写入临时文件
      const tmpPath = configPath + '.tmp';
      await fs.writeFile(tmpPath, finalContent, 'utf8');

      // 3. 原子替换
      await fs.move(tmpPath, configPath, { overwrite: true });

      logger.info('ConfigService', `Config saved for ${mode}`, { changedFields, restartRequired });
      return {
        success: true,
        restartRequired,
        changedFields,
        backupId,
        message: restartRequired
          ? '配置已保存，部分设置需要重启服务器后生效。'
          : '配置已保存。',
      };
    } catch (e) {
      logger.error('ConfigService', `Failed to save config for ${mode}`, e.message);
      throw e;
    }
  }

  /**
   * 从表单字段生成 serverconfig.txt 内容
   */
  _generateFromForm(mode, fields) {
    const lines = [];
    lines.push(`# ${mode === 'tmodloader' ? 'tModLoader' : 'Terraria'} Server Configuration`);
    lines.push(`# Generated by Terraria Panel`);

    // 按照 schema 顺序输出
    const fieldOrder = ['world', 'worldname', 'autocreate', 'difficulty', 'maxplayers',
                        'port', 'password', 'motd', 'secure', 'language', 'upnp', 'npcstream', 'priority'];

    for (const key of fieldOrder) {
      if (fields[key] !== undefined && fields[key] !== null && fields[key] !== '') {
        // 修正 world 路径
        if (key === 'world') {
          const worldsDir = getWorldsDir(mode);
          let worldPath = String(fields[key]);
          // 如果只是文件名，补全路径
          if (!worldPath.includes(path.sep) && !worldPath.includes('/')) {
            worldPath = path.join(worldsDir, worldPath);
          }
          lines.push(`${key}=${worldPath}`);
        } else {
          lines.push(`${key}=${fields[key]}`);
        }
      }
    }
    lines.push(''); // 尾随换行
    return lines.join('\n');
  }

  /**
   * 校验并修正配置内容
   * - 字段名必须在白名单中
   * - port 不能为 3001
   * - world 路径必须在模式 Worlds 目录下
   */
  _validate(content, mode) {
    const errors = [];
    const lines = content.split('\n');
    const correctedLines = [];
    const seenKeys = new Set();

    for (let line of lines) {
      const trimmed = line.trim();
      // 注释或空行保持原样
      if (trimmed.startsWith('#') || trimmed === '') {
        correctedLines.push(line);
        continue;
      }

      const eqIdx = trimmed.indexOf('=');
      if (eqIdx <= 0) {
        // 不合法行，保留但警告
        correctedLines.push(line);
        continue;
      }

      const key = trimmed.substring(0, eqIdx).trim().toLowerCase();
      const val = trimmed.substring(eqIdx + 1).trim();

      // 校验字段在白名单中
      if (!CONFIG_SCHEMA[key]) {
        errors.push(`未知配置字段: ${key}`);
        correctedLines.push(line); // 保留但标记
        continue;
      }

      // 检查重复字段，用最后一个
      if (seenKeys.has(key)) {
        logger.warn('ConfigService', `重复字段 ${key}，使用最后一个值`);
      }
      seenKeys.add(key);

      const schema = CONFIG_SCHEMA[key];

      // 类型校验
      if (schema.type === 'number') {
        const num = parseInt(val, 10);
        if (isNaN(num)) {
          errors.push(`${key} 必须是数字`);
          correctedLines.push(line);
          continue;
        }
        if (schema.min !== undefined && num < schema.min) {
          errors.push(`${key} 最小值为 ${schema.min}`);
        }
        if (schema.max !== undefined && num > schema.max) {
          errors.push(`${key} 最大值为 ${schema.max}`);
        }
      }

      if (schema.type === 'enum' && schema.values && !schema.values.includes(val)) {
        errors.push(`${key} 必须是以下值之一: ${schema.values.join(', ')}`);
      }

      if (schema.maxLength && val.length > schema.maxLength) {
        errors.push(`${key} 长度不能超过 ${schema.maxLength}`);
      }

      // 阻止 port=3001
      if (key === 'port' && val === '3001') {
        errors.push('游戏端口不能设置为 3001（面板端口冲突）');
      }

      // 阻止 world 路径越权
      if (key === 'world' && val) {
        const worldsDir = getWorldsDir(mode);
        const resolvedWorld = path.resolve(val);
        const resolvedWorldsDir = path.resolve(worldsDir);
        if (!resolvedWorld.startsWith(resolvedWorldsDir)) {
          errors.push(`world 路径必须位于 ${worldsDir} 目录下`);
        }
      }

      correctedLines.push(line);
    }

    return {
      valid: errors.length === 0,
      errors,
      corrected: correctedLines.join('\n'),
    };
  }

  _parse(content) {
    const result = {};
    content.split('\n').forEach(line => {
      const trimmed = line.trim();
      if (trimmed.startsWith('#') || trimmed === '') return;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx > 0) {
        const key = trimmed.substring(0, eqIdx).trim();
        const val = trimmed.substring(eqIdx + 1).trim();
        result[key] = val;
      }
    });
    return result;
  }

  getDefaultConfig(mode) {
    return DEFAULT_CONFIGS[mode] || DEFAULT_CONFIGS.vanilla;
  }
}

module.exports = ConfigService;
